insert into public.system_optimization_records (
  record_key,
  version,
  record_date,
  change_types,
  one_line_summary,
  why_changed,
  problems_found,
  main_changes,
  expected_result,
  database_changed,
  database_change_summary,
  screening_logic_changed,
  screening_logic_summary,
  automation_changed,
  automation_change_summary,
  old_data_impact,
  acceptance_result,
  unresolved_issues,
  next_step,
  important_decisions,
  technical_details,
  is_version_summary
) values (
  'v4.4.1-source-foundation',
  'V4.4.1',
  date '2026-09-20',
  array['数据修复', '自动化修复', '历史测试'],
  '这次把公司公告之外的政策、采购、产业统计和负面信息来源补进系统，并让每条信息都能看到从哪里来。',
  'V4.4历史验真发现，系统过去主要依赖公司公告，需求、产业、供应链和负面信息不足，无法证明回到历史当天时看到的信息是完整而且可得的。',
  jsonb_build_array(
    '公司公告占比过高，不能单独证明下游真的在买。',
    '旧信号的来源写法不统一，有些只写了“网络”或没有可核对的原文。',
    '来源是否登记、是否真的自动运行、是否能用于历史验证容易被混在一起。',
    '首次运行发现一条统计口径文字被误判成商业航天信号，已经保留记录并标为无效。'
  ),
  jsonb_build_array(
    '把来源统一分成公司、政策、需求、产业、供应链、市场、负面反证七类。',
    '接通中国政府网、政府采购网、国家统计局，并继续使用巨潮资讯和行情来源。',
    '每条原始信息和信号都补上来源、等级、发布时间、历史可得性和同源事件标记。',
    '增加每日七层覆盖检查，明确区分“成功检查但没有新信息”和“抓取失败”。',
    '在系统靠下位置增加信息源页面，信号、机会、公司、日报和历史验证都可以查看来源。',
    '旧数据没有删除；无法确认来源的旧记录明确标为D级，不能冒充正式证据。'
  ),
  '以后看任何重要信息，都能知道它来自哪里、可信度多高、是否真的自动采集、能不能用于历史验证；覆盖不足会直接显示，不再用登记数量冒充实际覆盖。',
  true,
  '增加了统一来源登记、七层每日覆盖和历史来源覆盖，并为原始信息和信号补充来源留痕。',
  false,
  '主筛选链和公司通过、观察、不通过的规则都没有改变，只补充输入来源和可追溯信息。',
  true,
  '每日流程现在会真实检查政策、政府采购、产业统计和公司公告，写入来源健康状态、去重结果和七层覆盖结果。',
  '旧信号、机会、公司、模型、日报和时间轴都保留。旧记录只补充来源说明；一条本次新发现的误判信号保留原记录但标为无效。',
  '部分通过',
  jsonb_build_array(
    '需求层目前主要依靠政府采购，下游客户财报和资本开支还没有统一自动采集。',
    '供应链层只覆盖已跟踪公司的公开披露，客户和竞争对手范围仍不完整。',
    '负面层目前主要来自法定公告关键词扫描，监管、客户和竞争对手的负面来源仍需扩充。',
    '市场行情只支持实时研究，不能直接作为严格历史验证价格来源。',
    '九条旧信号缺少可核对原文，已经标为D级，后续需要逐条补证。',
    'V4.4历史验真仍然是无效状态，本次扩容不能替代重新构建历史时点资料。'
  ),
  '先补齐三大赛道的下游客户、行业协会和负面监管来源，再用真实历史采集记录重新运行V4.4，不能用今天补到的资料假装当时已经获得。',
  jsonb_build_array(
    '来源已经登记，不等于已经自动运行。',
    '成功检查到零条新信息和抓取失败必须分开记录。',
    '市场价格只能验证市场共识，不能当作基本面事实。',
    '严格历史验证仍只接受当时真实可得、并且在判断前已经采集到的信息。',
    '信息源扩容以后，原来无效的V4.4测试不会自动变成有效。'
  ),
  jsonb_build_object(
    'pipeline_run_id', '01d0ff53-5ba7-4f09-b75b-8e473ffcddb2',
    'registered_sources', 24,
    'automated_sources', 7,
    'automatic_external_endpoints', 4,
    'source_categories', 7,
    'tests_passed', 11,
    'p0_count', 0
  ),
  true
)
on conflict (record_key) do update set
  version = excluded.version,
  record_date = excluded.record_date,
  change_types = excluded.change_types,
  one_line_summary = excluded.one_line_summary,
  why_changed = excluded.why_changed,
  problems_found = excluded.problems_found,
  main_changes = excluded.main_changes,
  expected_result = excluded.expected_result,
  database_changed = excluded.database_changed,
  database_change_summary = excluded.database_change_summary,
  screening_logic_changed = excluded.screening_logic_changed,
  screening_logic_summary = excluded.screening_logic_summary,
  automation_changed = excluded.automation_changed,
  automation_change_summary = excluded.automation_change_summary,
  old_data_impact = excluded.old_data_impact,
  acceptance_result = excluded.acceptance_result,
  unresolved_issues = excluded.unresolved_issues,
  next_step = excluded.next_step,
  important_decisions = excluded.important_decisions,
  technical_details = excluded.technical_details,
  is_version_summary = excluded.is_version_summary;
