WITH s AS (SELECT * FROM mainline.daily_mainline_snapshot WHERE run_id='382be957-d400-4d09-b2ac-8507a166a0e8'),
 refs AS (SELECT DISTINCT unnest(source_snapshot_ids) id FROM s),
 per AS (SELECT s.as_of_date,s.object_id, count(distinct x.dataset_code) FILTER(WHERE x.dataset_code IN ('membership_snapshot','stock_window','trading_calendar')) n FROM s CROSS JOIN LATERAL unnest(s.source_snapshot_ids) r(id) LEFT JOIN mainline.source_snapshots x ON x.source_snapshot_id=r.id GROUP BY 1,2),
 a AS (SELECT count(*)::int formal_snapshots,count(*) FILTER(WHERE critical_data_ok)::int critical_pass,count(*) FILTER(WHERE stage_frozen)::int frozen,count(*) FILTER(WHERE sector_return IS NOT NULL AND up_ratio IS NOT NULL AND above_ma20 IS NOT NULL AND above_ma60 IS NOT NULL AND new_high_60 IS NOT NULL)::int sector_and_breadth_available,count(*) FILTER(WHERE benchmark_return IS NOT NULL AND (metric_coverage_json->>'benchmark')::numeric>=0.95)::int benchmark_pass,count(*) FILTER(WHERE rs_5 IS NULL AND rs_10 IS NULL AND rs_20 IS NULL AND turnover_share IS NULL AND turnover_intensity IS NULL)::int dependent_null,count(*) FILTER(WHERE turnover_cap_deviation IS NULL AND top3_return_contribution IS NULL)::int deferred_null,min((metric_coverage_json->>'OHLCV')::numeric) min_ohlcv_coverage,min((metric_coverage_json->>'amount')::numeric) min_amount_coverage,count(*) FILTER(WHERE (decision_reason->>'effective_membership_pit')::boolean)::int membership_pit_pass FROM s),
 l AS (SELECT count(*) FILTER(WHERE x.source_snapshot_id IS NULL)::int dangling_refs,count(*) FILTER(WHERE x.source_snapshot_id IS NOT NULL AND r.provider_code IS NULL)::int unregistered_sources FROM refs f LEFT JOIN mainline.source_snapshots x ON x.source_snapshot_id=f.id LEFT JOIN mainline.source_registry r ON r.provider_code=x.source_id AND r.dataset_code=x.dataset_code),
 m AS (SELECT count(*)::int manifest_count,bool_and((error_summary->>'deterministic_repeatability')::boolean) repeatable FROM mainline.run_manifests WHERE run_id IN ('382be957-d400-4d09-b2ac-8507a166a0e8','2a9c9c7c-62e1-485d-baae-4529630deac6'))
SELECT a.*,l.*,m.*, (SELECT count(*)::int FROM per WHERE n=3) membership_price_calendar_chains,(SELECT count(*)::int FROM mainline.source_snapshots WHERE metadata->>'run_id'='382be957-d400-4d09-b2ac-8507a166a0e8') new_source_snapshots,
(SELECT count(*)::int FROM mainline.trading_calendar) calendar_rows,
CASE WHEN formal_snapshots=15 AND critical_pass=15 AND benchmark_pass=15 AND frozen=0 AND dangling_refs=0 AND unregistered_sources=0 AND manifest_count=2 AND repeatable THEN 'PASS' ELSE 'FAIL' END "G1",
(formal_snapshots=15 AND critical_pass=15 AND benchmark_pass=15 AND frozen=0 AND dangling_refs=0 AND unregistered_sources=0 AND manifest_count=2 AND repeatable) "READY_FOR_PRODUCTION_ENABLEMENT"
FROM a,l,m;
