import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {businessDate,windowFor,CRON,mainlineDecision,overallStatus,independently,stampPayload,latestSuccessful} from '../supabase/functions/v43-daily-pipeline/policy.mjs';
test('09 UTC equals 17 Shanghai',()=>{assert.equal(CRON,'0 9 * * *');assert.equal(new Date(windowFor('2026-10-02').cutoff_at).getUTCHours(),9)});
test('UTC midnight boundary uses Shanghai business date',()=>{assert.equal(businessDate('2026-10-01T16:01:00Z'),'2026-10-02');assert.equal(windowFor('2026-10-02').start_at,'2026-10-01T16:00:00.000Z')});
test('invalid date rejected',()=>assert.throws(()=>windowFor('2026-02-30')));
test('disabled provider on confirmed trading day',()=>assert.deepEqual(mainlineDecision(true),{status:'skipped',reason:'pending_provider',provider_enabled:false,gate:'G1_NOT_PASSED'}));
test('holiday does not use weekday guesses',()=>assert.equal(mainlineDecision(false).reason,'skipped_non_trading_day'));
test('unknown calendar stays skipped',()=>assert.equal(mainlineDecision(null).reason,'trading_calendar_unknown'));
test('success plus disabled mainline completes',()=>assert.equal(overallStatus([{status:'succeeded'},{status:'skipped'}]),'succeeded'));
test('mainline error does not prevent sector',async()=>{let saved=0;const a=await independently('mainline',async()=>{throw new Error('broken')});const b=await independently('sector',async()=>{saved++;return {status:'succeeded'}});assert.equal(saved,1);assert.equal(a.status,'failed');assert.equal(overallStatus([a,b]),'partial')});
test('sector failure preserves previous mainline result',async()=>{const a=await independently('mainline',async()=>({status:'succeeded',snapshot:'kept'}));const b=await independently('sector',async()=>{throw new Error('broken')});assert.equal(a.snapshot,'kept');assert.equal(overallStatus([a,b]),'partial')});
test('timeout aborts signal and is bounded',async()=>{let aborted=false;const r=await independently('hung',signal=>new Promise(()=>signal.addEventListener('abort',()=>aborted=true)),5);assert.equal(r.status,'failed');assert.equal(aborted,true)});
test('same-day and historical records distinguished',()=>{const c={...windowFor('2026-10-02'),pipeline_run_id:'r'};assert.equal(stampPayload({published_at:'2026-10-02T02:00:00Z'},c).metadata.information_window,'same_day');assert.equal(stampPayload({published_at:'2026-10-01T02:00:00Z'},c).metadata.information_window,'historical_lookback')});
test('after cutoff marked, next day rejected',()=>{const c=windowFor('2026-10-02');assert.equal(stampPayload({published_at:'2026-10-02T10:00:00Z'},c).metadata.information_window,'after_cutoff');assert.throws(()=>stampPayload({published_at:'2026-10-02T16:00:00Z'},c))});
test('missing source time remains NULL',()=>{const x=stampPayload({metadata:{original:true}},windowFor('2026-10-02'));assert.equal(x.metadata.source_time,null);assert.equal(x.metadata.original,true);assert.ok(x.metadata.fetched_at)});
test('failed today selects immutable prior success',()=>{const old={finished_at:'2026-10-01',metadata:{jobs:{three_sector_daily_job:{status:'succeeded'}},successful_report:{id:'old'}}};const now={finished_at:'2026-10-02',metadata:{jobs:{three_sector_daily_job:{status:'failed'}},successful_report:{id:'bad'}}};assert.equal(latestSuccessful([now,old]).metadata.successful_report.id,'old')});
test('providers stay in Workflow and dispatch stays behind production gate',()=>{const c=readFileSync(new URL('../supabase/functions/v43-daily-pipeline/index.ts',import.meta.url),'utf8');assert.ok(!/pytdx|akshare|tushare|phase1f_free/.test(c));assert.ok(c.includes('if(!production.enabled)'));assert.ok(c.includes('MAINLINE_DISPATCH_CREDENTIAL_NOT_CONFIGURED'));assert.ok(c.includes('dispatch_accepted_business_pending'));assert.ok(c.includes('await dispatchMainline(runDate,run.id,"production",signal)')); assert.ok(c.includes('recordStep'));});

test('dispatch remains running until business completion',()=>assert.equal(overallStatus([{status:'dispatched'},{status:'succeeded'},{status:'succeeded'}]),'running'));
