'use client';
import {useEffect,useState,useRef,type ReactNode} from 'react';
import {Activity,ArrowRight,Database,ShieldCheck,Snowflake,Info} from 'lucide-react';
import {Shell} from '../research-ui';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Popover,PopoverTrigger,PopoverContent} from '@/components/ui/popover';
import {labels,meanings,standards,fields,compatible,VERSION_WARNING,pct,number,show,mode,status,event,reason,ruleName,evidenceSummary,remaining,readable,operator,lifecycleOf,coverageName} from './ui-copy';

type Row={snapshot:Record<string,any>;state:Record<string,any>;rules:any[]};
type Data={system_version:string;rule_version:string;parameter_profile:string;data_date:string|null;latest_success_date:string|null;latest_simulation_date:string|null;latest_attempt_date:string|null;latest_run_status:string|null;production_enabled:boolean;display_run_type:string;state_counts:Record<string,number>;gates:Record<string,string>;rows:Row[];changes:any[];sources:any[];quality:any[];detail:Row|null;timeline:any[];rule_evidence:any[];lifecycle:any;latest_attempt:any};
function Explain({title,children}:{title:string;children:ReactNode}){
 const [open,setOpen]=useState(false);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const enter=()=>{if(timer.current)clearTimeout(timer.current);setOpen(true);};
 const leave=()=>{timer.current=setTimeout(()=>setOpen(false),180);};
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);},[]);
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><button type="button" className="ml-info" aria-label={`${title}说明`} onPointerEnter={e=>{if(e.pointerType==='mouse')enter();}} onPointerLeave={e=>{if(e.pointerType==='mouse')leave();}}><Info size={15}/></button></PopoverTrigger><PopoverContent className="ml-explanation" collisionPadding={16} onPointerEnter={enter} onPointerLeave={leave} onOpenAutoFocus={e=>e.preventDefault()}><strong>{title}</strong>{children}</PopoverContent></Popover>;
}
const stage=(s:string)=><span className={`ml-stage stage-${s}`}>{s} · {labels[s]||'状态待核验'}</span>;
function Audit({title,children}:{title:string;children:ReactNode}){return <details className="ml-audit"><summary>{title}</summary>{children}</details>;}
function Raw({value}:{value:any}){return <pre>{JSON.stringify(value,null,2)}</pre>;}
const joined=(list:{name:string}[])=>list.map(x=>x.name).join('、')||'无';
function StateFacts({row,ok}:{row:Row;ok:boolean}){
 const s=row.state,life=s.checkpoint?.lifecycle||{},sum=evidenceSummary(row.rules,s.state);
 const candidate=evidenceSummary(row.rules,'S0');
 const dates:Record<string,string>= {S1:`进入候选 ${show(life.candidate_at)}`,S2:`主线确认 ${show(life.confirmed_at)}`,S3:`开始转弱 ${show(life.weakened_at)}`,S4:`进入退潮 ${show(life.closed_at||life.end_date)}`};
 return <div className="ml-stage-facts"><p>{dates[s.state]||'尚未形成候选'}</p><p>今日{['S1','S2'].includes(s.state)?'确认':s.state==='S3'?'转弱':s.state==='S4'?'退潮':'候选'}条件：{sum.passed.length} / {sum.total}组满足{sum.unknown.length>0?`，${sum.unknown.length}组数据不足`:''}</p>{s.state==='S1'&&<p>候选迹象已满足：{joined(candidate.passed)}</p>}<p>今日已满足：{joined(sum.passed)}</p>{s.state==='S3'&&<p>重新确认条件：{row.rules.find(q=>q.rule_id==='recover')?.passed===true?'今日满足':row.rules.find(q=>q.rule_id==='recover')?.passed===false?'今日未满足':'数据不足'}</p>}{s.state==='S4'&&<p>本轮 {show(life.start_date)} 至 {show(life.end_date||life.closed_at)}；重新进入 {show(s.reentry_count)} 次</p>}<p>{remaining(s,row.rules,ok)}</p>{s.stage_frozen&&<p>暂缓原因：{reason(s.freeze_reason)}；沿用上一状态。</p>}</div>;
}
function Outcome({row,ok}:{row:Row;ok:boolean}){
 const sum=evidenceSummary(row.rules,row.state.state);
 return <div className="ml-outcome"><p className="ml-muted">今日{['S1','S2'].includes(row.state.state)?'确认':row.state.state==='S3'?'转弱':row.state.state==='S4'?'退潮':'候选'}条件结果</p><p><b>已满足：</b>{joined(sum.passed)}</p><p><b>尚未满足：</b>{joined(sum.failed)}</p><p><b>数据不足：</b>{joined(sum.unknown)}</p><p><b>还差什么：</b>{remaining(row.state,row.rules,ok)}</p></div>;
}
function Coverage({row}:{row:Row}){
 const coverage=row.snapshot.metric_coverage_json||{},s=row.state;
 return <><div className="ml-outcome"><p>关键数据：{row.snapshot.critical_data_ok===true?'完整':row.snapshot.critical_data_ok===false?'不足':'未提供完整度结论'}</p>{Object.entries(coverage).map(([k,v])=><p key={k}>{coverageName(k)}完整度：{typeof v==='number'?pct(v):typeof v==='boolean'?(v?'完整':'不足'):'详见技术记录'}</p>)}<p>判断状态：{s.stage_frozen?'暂缓判断':'正常判断'}</p><p>暂缓原因：{reason(s.freeze_reason)}</p><p>连续计数处理：{s.stage_frozen?'连续条件计数暂停':reason(s.checkpoint?.counter_policy||s.counter_policy)}</p></div><Audit title="完整度技术记录"><Raw value={{coverage,critical_data_ok:row.snapshot.critical_data_ok,stage_frozen:s.stage_frozen,freeze_reason:s.freeze_reason,counter_policy:s.checkpoint?.counter_policy}}/></Audit></>;
}
export default function MainlinePage(){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<Data|null>(null);const [detailError,setDetailError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/mainline',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('真实数据读取失败');return r.json();}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(String(e.message));});return()=>{active=false;};},[]);
 useEffect(()=>{if(!selected)return;let active=true;setDetail(null);setDetailError('');fetch(`/api/mainline?kind=detail&object=${encodeURIComponent(selected)}&date=${data?.data_date||''}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('行业详情读取失败');return r.json();}).then(d=>{if(active)setDetail(d);}).catch(e=>{if(active)setDetailError(e.message);});return()=>{active=false;};},[selected,data?.data_date]);
 const rows=data?.rows||[],current=detail?.detail;const ok=compatible(data?.rule_version,data?.parameter_profile),detailOk=compatible(detail?.rule_version,detail?.parameter_profile);
 const life=lifecycleOf(detail?.lifecycle,current?.state||{});
 const cards=(list:Row[])=>list.length?<div className="ml-sector-grid">{list.map(r=><button className="ml-sector-card" key={r.snapshot.object_id} onClick={()=>setSelected(r.snapshot.object_id)}><div><strong>{r.snapshot.industry_name}</strong>{stage(r.state.state)}</div><p>10日相对强度 {pct(r.snapshot.rs_10)}<span>持续 {show(r.state.state_days)} 日</span></p><StateFacts row={r} ok={ok}/>{r.state.stage_frozen&&<small><Snowflake size={13}/>暂缓判断</small>}<span className="ml-card-link">查看原因与时间轴 <ArrowRight size={14}/></span></button>)}</div>:<div className="ml-empty">该日期没有符合此状态的真实行业。</div>;
 const metricHead=(f:typeof fields[number])=><span className="ml-label-info">{f.label}<Explain title={f.label}><p>{f.help}</p></Explain></span>;
 return <Shell active="A股主线"><main className="mainline-page ml-live-page">
  <header className="mainline-hero"><div><p className="eyebrow">行业状态 · 真实数据</p><h1>A股主线雷达 · V2.2.1</h1><p>先看谁正在形成主线，再看为什么、还差什么、是否转弱。</p></div><div className="mainline-live warn"><Activity size={16}/>{data?(data.production_enabled?'生产已启用':'生产未启用'):'正在核对生产状态'}</div></header>
  {error&&<div role="alert" className="ml-notice">{error}。页面不会用假数据替代。</div>}
  {!data&&!error&&<div className="ml-empty">正在读取真实板块快照…</div>}
  {data&&<>
   <section className="ml-notice"><Database size={18}/><div><strong>{mode(data.display_run_type)}</strong><p>当前展示 {show(data.data_date)} 的{mode(data.display_run_type).replace('数据','')}结果；{data.latest_success_date?`最近正式生产成功日为 ${data.latest_success_date}。`:data.production_enabled?'正式生产已启用，等待下一个真实交易日自动运行。':'正式生产未启用，尚无正式生产成功记录。'}</p></div></section>
   <section className="ml-meta"><div><span>最近正式生产日</span><strong>{data.latest_success_date||'尚无'}</strong></div><div><span>最近演练日期</span><strong>{show(data.latest_simulation_date)}</strong></div><div><span>最近运行日期</span><strong>{show(data.latest_attempt_date)}</strong></div><div><span>最近运行状态</span><strong>{status(data.latest_run_status)}</strong></div></section>
   {!ok&&<p className="ml-version-warning" role="status">{VERSION_WARNING}</p>}
   <section className="ml-distribution">{['S0','S1','S2','S3','S4','Frozen'].map(s=><div key={s}><div className="ml-distribution-title">{s==='Frozen'?<span className="ml-stage"><Snowflake size={13}/>暂缓判断</span>:stage(s)}<Explain title={`${s==='Frozen'?'':s+' · '}${labels[s]}`}><p>{meanings[s]}</p>{ok?standards[s].map(t=><p key={t}>{t}</p>):<p>{VERSION_WARNING}</p>}</Explain></div><strong>{show(data.state_counts[s==='Frozen'?'frozen_count':`${s}_count`])}</strong><small>{s==='Frozen'?'保留上一可信状态':'点击说明查看标准'}</small></div>)}</section>
   <section className="mainline-panel ml-changes"><h2>今日状态变化</h2>{data.changes.length?data.changes.map(x=><button key={x.object_id} onClick={()=>setSelected(x.object_id)}><strong>{x.industry_name}</strong><span>{event(x.transition.from_state==='S4'?'new_lifecycle_reentry':x.transition.trigger_rule)}</span><small>{x.transition.from_state}<ArrowRight size={14}/>{x.transition.to_state}{x.transition.from_state==='S4'?' · 新生命周期':''}</small></button>):<p>该交易日没有已生效的状态转移。</p>}</section>
   <Tabs defaultValue="radar"><TabsList className="ml-tabs">{[['radar','全市场雷达'],['S1','S1 正在形成'],['S2','S2 主线确认'],['S3','S3 主线转弱'],['S4','S4 主线退潮'],['frozen','暂缓判断'],['quality','质量与来源']].map(([k,v])=><TabsTrigger value={k} key={k}>{v}</TabsTrigger>)}</TabsList>
    <TabsContent value="radar"><div className="mainline-panel mainline-table-wrap"><Table><TableHeader><TableRow><TableHead>行业 / 日期</TableHead><TableHead>当前 / 前态</TableHead><TableHead><span className="ml-label-info">持续天数<Explain title="持续天数"><p>当前状态的已保存交易日数，包含暂缓期间；与暂停的连续条件计数不同。</p></Explain></span></TableHead>{fields.map(f=><TableHead key={f.key}>{metricHead(f)}</TableHead>)}<TableHead>判断状态</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.snapshot.object_id}><TableCell><button className="ml-name" onClick={()=>setSelected(r.snapshot.object_id)}>{r.snapshot.industry_name}</button><small className="ml-sub">{r.snapshot.as_of_date}</small></TableCell><TableCell>{stage(r.state.state)}<small className="ml-sub">前态 {labels[r.state.previous_state]||'—'} {r.state.previous_state}</small></TableCell><TableCell>{show(r.state.state_days)}</TableCell>{fields.map(f=><TableCell key={f.key}>{f.key==='turnover_intensity'?number(r.snapshot[f.key]):pct(r.snapshot[f.key])}</TableCell>)}<TableCell>{r.state.stage_frozen?<span title={reason(r.state.freeze_reason)}>暂缓判断</span>:'正常'}</TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
    {['S1','S2','S3','S4'].map(s=><TabsContent value={s} key={s}>{cards(rows.filter(r=>r.state.state===s))}</TabsContent>)}<TabsContent value="frozen">{cards(rows.filter(r=>r.state.stage_frozen))}</TabsContent>
    <TabsContent value="quality"><div className="mainline-panel"><h2>数据质量</h2>{data.quality.map(q=><div key={q.quality_id} className="ml-quality"><strong>{q.as_of_date} · 数据集 {q.dataset_code}</strong><p>实际条数 / 应有条数 {q.actual_count} / {q.expected_count} · 缺失 {q.missing_count} · 重复 {q.duplicate_count} · 数据完整度 {pct(q.completeness_ratio)}</p><p>是否暂缓判断：{q.stage_frozen?'是':'否'} · 原因：{reason(q.freeze_reason)}</p><Audit title="数据质量技术记录"><Raw value={q}/></Audit></div>)}<h2>数据来源</h2>{data.sources.map(s=><div className="ml-source" key={s.id}><strong>数据来源：{s.source} · 数据集：{s.dataset}</strong><p>版本：{s.version}</p><Audit title="来源审计：校验值与证据位置"><Raw value={s}/></Audit></div>)}</div></TabsContent>
   </Tabs>
   <footer className="ml-footer"><ShieldCheck size={16}/><span>验收状态：{Object.entries(data.gates||{}).map(([g,v])=>`${g} ${v==='PASS'?'已通过':v==='FAIL'?'未通过':'待核验'}`).join(' / ')}</span><Audit title="规则与参数版本"><p>规则版本：{data.rule_version}<br/>参数版本：{data.parameter_profile}</p><Raw value={{latest_attempt:data.latest_attempt,gates:data.gates}}/></Audit><p>本模块识别行业主线；公司利润、估值、赔率和投资价值继续由三大赛道研究模块处理。</p></footer>
  </>}
  <Sheet open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="ml-detail" side="right"><SheetHeader><SheetTitle>{current?.snapshot.industry_name||'行业详情'}</SheetTitle><SheetDescription>先看状态与原因，再核对指标和证据；缺失值保持空缺。</SheetDescription></SheetHeader>{detailError?<div role="alert">{detailError}</div>:!current?<p>读取详情中…</p>:<div className="ml-detail-body">
   <div className="ml-detail-status">{stage(current.state.state)}<span>前态 {labels[current.state.previous_state]||'—'} · 持续 {current.state.state_days} 个交易日</span></div><p>{current.snapshot.as_of_date} · {mode(detail?.display_run_type)}</p><p>{current.state.stage_frozen?meanings.Frozen:`当前处于“${labels[current.state.state]}”。${reason(current.state.reason)}。今日条件见下方，持有状态不等于今日全部条件满足。`}</p>
   <h3>为什么是这个状态</h3><Outcome row={current} ok={detailOk}/><Audit title="技术规则详情"><Raw value={{reason:current.state.reason,trigger_rules:current.state.trigger_rules,failed_rules:current.state.failed_rules,unavailable_rules:current.state.unavailable_rules,consecutive_days:current.state.consecutive_days,checkpoint:current.state.checkpoint}}/></Audit>
   <h3>关键指标</h3><div className="ml-metrics">{fields.map(f=><div key={f.key}><span>{metricHead(f)}</span><strong>{f.key==='turnover_intensity'?number(current.snapshot[f.key]):pct(current.snapshot[f.key])}</strong></div>)}</div>
   <h3>状态条件</h3><div className="ml-outcome"><p><b>进入当前状态的标准：</b>{detailOk?standards[current.state.state]?.[0]:VERSION_WARNING}</p><Audit title="完整状态标准">{detailOk?standards[current.state.state]?.map(t=><p key={t}>{t}</p>):<p>{VERSION_WARNING}</p>}</Audit><Outcome row={current} ok={detailOk}/></div>
   <h3>指标趋势</h3><p className="ml-muted">逐日对比已保存的真实指标；表格可横向滚动，空缺保持为空。</p><div className="mainline-table-wrap"><Table><TableHeader><TableRow><TableHead>日期</TableHead><TableHead>状态</TableHead>{fields.map(f=><TableHead key={f.key}>{f.label}</TableHead>)}</TableRow></TableHeader><TableBody>{detail?.timeline.map(t=><TableRow key={t.date}><TableCell>{t.date}</TableCell><TableCell>{stage(t.state.state)}</TableCell>{fields.map(f=><TableCell key={f.key}>{f.key==='turnover_intensity'?number(t.metrics?.[f.key]):pct(t.metrics?.[f.key])}</TableCell>)}</TableRow>)}</TableBody></Table></div>
   <h3>状态时间轴</h3><p className="ml-muted">仅列出已持久化日期，日期空档不会补造状态。</p><ol className="ml-timeline">{detail?.timeline.map(t=><li key={t.date}><strong>{t.date}</strong>{stage(t.state.state)}<small>{t.state.transition?`${event(t.state.transition.from_state==='S4'?'new_lifecycle_reentry':t.state.transition.trigger_rule)} · ${t.state.transition.from_state} → ${t.state.transition.to_state}`:reason(t.state.reason)}</small><Audit title="当日状态技术记录"><Raw value={t.state}/></Audit></li>)}</ol>
   <h3>规则证据</h3><div className="mainline-table-wrap"><Table><TableHeader><TableRow><TableHead>规则</TableHead><TableHead>实际值</TableHead><TableHead>标准</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{detail?.rule_evidence.map(q=><TableRow key={q.rule_id}><TableCell>{ruleName(q.rule_id)}<small className="ml-sub">{q.rule_id}</small></TableCell><TableCell>{readable(q.actual_value,q)}</TableCell><TableCell>{operator(q.operator)} {readable(q.threshold,q)}</TableCell><TableCell>{q.passed==null?(/enhancement_evidence_deferred/.test(q.reason||'')?'暂未启用':'数据不足'):q.passed?'满足':'未满足'}<small className="ml-sub">{reason(q.reason)}</small></TableCell></TableRow>)}</TableBody></Table></div><Audit title="原始规则证据"><Raw value={detail?.rule_evidence}/></Audit>
   <h3>生命周期</h3><div className="ml-life">{Object.entries({本轮开始:life?.start_date,进入候选:life?.candidate_at,主线确认:life?.confirmed_at,开始转弱:life?.weakened_at,进入退潮:life?.closed_at,本轮结束:life?.end_date,最高状态:life?.highest_state?`${life.highest_state} · ${labels[life.highest_state]||'状态待核验'}`:'—',重新进入次数:current.state.reentry_count}).map(([k,v])=><p key={k}><span>{k}</span><strong>{show(v)}</strong></p>)}</div><Audit title="生命周期技术详情"><Raw value={{lifecycle:detail?.lifecycle,checkpoint_lifecycle:current.state.checkpoint?.lifecycle,lifecycle_id:current.state.lifecycle_id,reentry_count:current.state.reentry_count}}/></Audit>
   <h3>数据完整度与暂缓判断</h3><Coverage row={current}/><Audit title="来源与版本"><p>规则版本：{detail?.rule_version}</p><p>参数版本：{detail?.parameter_profile}</p><p>运行编号：{current.state.run_id}</p><Raw value={{rule_version:detail?.rule_version,profile:detail?.parameter_profile,run_id:current.state.run_id,sources:detail?.sources,latest_attempt:detail?.latest_attempt,snapshot:current.snapshot}}/></Audit>
  </div>}</SheetContent></Sheet>
 </main></Shell>;
}
