'use client';
import {useEffect,useState} from 'react';
import {Activity,ArrowRight,Database,ShieldCheck,Snowflake} from 'lucide-react';
import {Shell} from '../research-ui';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';

type Row={snapshot:Record<string,any>;state:Record<string,any>;rules:any[]};
type Data={system_version:string;rule_version:string;parameter_profile:string;data_date:string|null;latest_success_date:string|null;latest_simulation_date:string|null;latest_attempt_date:string|null;latest_run_status:string|null;production_enabled:boolean;display_run_type:string;state_counts:Record<string,number>;gates:Record<string,string>;rows:Row[];changes:any[];sources:any[];quality:any[];detail:Row|null;timeline:any[];rule_evidence:any[];lifecycle:any;latest_attempt:any};
const labels:Record<string,string>={S0:'未入候选',S1:'候选主线',S2:'确认主线',S3:'转弱',S4:'退潮'};
const show=(v:any)=>v===null||v===undefined?'—':String(v);
const pct=(v:any)=>v==null?'—':`${(Number(v)*100).toFixed(1)}%`;
const number=(v:any)=>v==null?'—':Number(v).toFixed(2);
const stage=(s:string)=><span className={`ml-stage stage-${s}`}>{s} · {labels[s]||s}</span>;
export default function MainlinePage(){
 const [data,setData]=useState<Data|null>(null);const [error,setError]=useState('');const [selected,setSelected]=useState<string|null>(null);const [detail,setDetail]=useState<Data|null>(null);const [detailError,setDetailError]=useState('');
 useEffect(()=>{let active=true;fetch('/api/mainline',{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('真实数据读取失败');return r.json();}).then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(String(e.message));});return()=>{active=false;};},[]);
 useEffect(()=>{if(!selected)return;let active=true;setDetail(null);setDetailError('');fetch(`/api/mainline?kind=detail&object=${encodeURIComponent(selected)}&date=${data?.data_date||''}`,{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('行业详情读取失败');return r.json();}).then(d=>{if(active)setDetail(d);}).catch(e=>{if(active)setDetailError(e.message);});return()=>{active=false;};},[selected,data?.data_date]);
 const rows=data?.rows||[];const current=detail?.detail;const fields=[['rs_5','RS 5'],['rs_10','RS 10'],['rs_20','RS 20'],['rs_10_pct','RS10分位'],['turnover_share','成交额占比'],['turnover_intensity','成交强度'],['up_ratio','上涨占比'],['above_ma20','MA20之上'],['above_ma60','MA60之上'],['new_high_60','60日新高']];
 const cards=(list:Row[])=>list.length?<div className="ml-sector-grid">{list.map(r=><button className="ml-sector-card" key={r.snapshot.object_id} onClick={()=>setSelected(r.snapshot.object_id)}><div><strong>{r.snapshot.industry_name}</strong>{stage(r.state.state)}</div><p>RS10 {pct(r.snapshot.rs_10)}<span>持续 {show(r.state.state_days)} 日</span></p>{r.state.stage_frozen&&<small><Snowflake size={13}/>{r.state.freeze_reason}</small>}<span className="ml-card-link">查看规则与时间轴 <ArrowRight size={14}/></span></button>)}</div>:<div className="ml-empty">该日期没有符合此状态的真实行业。</div>;
 return <Shell active="A股主线"><main className="mainline-page ml-live-page">
  <header className="mainline-hero"><div><p className="eyebrow">MARKET RADAR / {data?.system_version||'数据读取中'}</p><h1>A股主线识别</h1><p>先看行业状态，再核对变化、规则与证据。</p></div><div className="mainline-live warn"><Activity size={16}/>{data?.production_enabled?'生产已启用':'Production not enabled'}</div></header>
  {error&&<div role="alert" className="ml-notice">{error}。页面不会用假数据替代。</div>}
  {!data&&!error&&<div className="ml-empty">正在读取真实板块快照…</div>}
  {data&&<>
   <section className="ml-notice"><Database size={18}/><div><strong>{data.display_run_type==='production'?'真实生产快照':data.display_run_type==='production_simulation'?'SIMULATION · 真实数据演练快照':'BACKFILL · 历史回填快照'}</strong><p>当前展示交易日 {show(data.data_date)}。{data.latest_success_date?`正式生产最近成功日 ${data.latest_success_date}`:'正式生产尚无成功记录。'} simulation数据单独标记。</p></div></section>
   <section className="ml-meta"><div><span>正式生产成功日</span><strong>{data.latest_success_date||'尚无'}</strong></div><div><span>最近simulation</span><strong>{show(data.latest_simulation_date)}</strong></div><div><span>最近尝试日期</span><strong>{show(data.latest_attempt_date)}</strong></div><div><span>最近运行状态</span><strong>{show(data.latest_run_status)}</strong></div></section>
   <section className="ml-distribution">{Object.entries(labels).map(([s,label])=><div key={s}>{stage(s)}<strong>{show(data.state_counts[`${s}_count`])}</strong><small>{label}</small></div>)}<div><span className="ml-stage"><Snowflake size={13}/> Frozen</span><strong>{show(data.state_counts.frozen_count)}</strong><small>冻结期间保留原状态</small></div></section>
   <section className="mainline-panel ml-changes"><h2>今日状态变化</h2>{data.changes.length?data.changes.map(x=><button key={x.object_id} onClick={()=>setSelected(x.object_id)}><strong>{x.industry_name}</strong>{x.transition.from_state}<ArrowRight size={14}/>{x.transition.to_state}<small>{x.transition.trigger_rule}{x.transition.from_state==='S4'?' · 新生命周期':''}</small></button>):<p>该交易日没有已生效的状态转移。</p>}</section>
   <Tabs defaultValue="radar"><TabsList className="ml-tabs">{[['radar','全市场雷达'],['S1','S1 候选'],['S2','S2 确认'],['S3','S3 转弱'],['S4','S4 退潮'],['frozen','Frozen'],['quality','质量与来源']].map(([k,v])=><TabsTrigger value={k} key={k}>{v}</TabsTrigger>)}</TabsList>
    <TabsContent value="radar"><div className="mainline-panel mainline-table-wrap"><Table><TableHeader><TableRow><TableHead>行业 / 日期</TableHead><TableHead>当前 / 前态</TableHead><TableHead>持续天数</TableHead>{fields.map(([k,label])=><TableHead key={k}>{label}</TableHead>)}<TableHead>冻结</TableHead><TableHead>run_id</TableHead></TableRow></TableHeader><TableBody>{rows.map(r=><TableRow key={r.snapshot.object_id}><TableCell><button className="ml-name" onClick={()=>setSelected(r.snapshot.object_id)}>{r.snapshot.industry_name}</button><small className="ml-sub">{r.snapshot.as_of_date}</small></TableCell><TableCell>{stage(r.state.state)}<small className="ml-sub">前态 {show(r.state.previous_state)}</small></TableCell><TableCell>{show(r.state.state_days)}</TableCell>{fields.map(([k])=><TableCell key={k}>{k==='turnover_intensity'?number(r.snapshot[k]):pct(r.snapshot[k])}</TableCell>)}<TableCell>{r.state.stage_frozen?<span title={r.state.freeze_reason}>Frozen · {r.state.freeze_reason}</span>:'正常'}</TableCell><TableCell><code title={r.state.run_id}>{show(r.state.run_id)}</code></TableCell></TableRow>)}</TableBody></Table></div></TabsContent>
    {['S1','S2','S3','S4'].map(s=><TabsContent value={s} key={s}>{cards(rows.filter(r=>r.state.state===s))}</TabsContent>)}<TabsContent value="frozen">{cards(rows.filter(r=>r.state.stage_frozen))}</TabsContent>
    <TabsContent value="quality"><div className="mainline-panel"><h2>数据质量</h2>{data.quality.map(q=><div key={q.quality_id} className="ml-quality"><strong>{q.as_of_date} · {q.dataset_code}</strong><p>实际 / 预期 {q.actual_count} / {q.expected_count} · 缺失 {q.missing_count} · 重复 {q.duplicate_count} · 覆盖 {pct(q.completeness_ratio)}</p><p>冻结 {String(q.stage_frozen)} · {JSON.stringify(q.freeze_reason)}</p></div>)}<h2>真实来源与校验</h2>{data.sources.map(s=><div className="ml-source" key={s.id}><strong>{s.source} · {s.dataset}</strong><p>{s.version}</p><code>{s.checksum}</code><p>{s.evidence_location}</p></div>)}</div></TabsContent>
   </Tabs>
   <footer className="ml-footer"><ShieldCheck size={16}/>{Object.entries(data.gates||{}).map(([g,v])=><span key={g}>{g} = {v}</span>)}<p>{data.rule_version}<br/>{data.parameter_profile}</p><p>本模块识别行业主线；公司利润、估值、赔率和投资价值继续由三大赛道研究模块处理。</p></footer>
  </>}
  <Sheet open={Boolean(selected)} onOpenChange={open=>{if(!open)setSelected(null);}}><SheetContent className="ml-detail" side="right"><SheetHeader><SheetTitle>{current?.snapshot.industry_name||'行业详情'}</SheetTitle><SheetDescription>直接读取真实状态、规则与来源；缺失值保持空缺。</SheetDescription></SheetHeader>{detailError?<div role="alert">{detailError}</div>:!current?<p>读取详情中…</p>:<div className="ml-detail-body">
   <div className="ml-detail-status">{stage(current.state.state)}<span>前态 {current.state.previous_state} · 持续 {current.state.state_days} 日</span></div><p>{current.snapshot.as_of_date} · {detail?.display_run_type}</p>
   <h3>规则记录的状态原因</h3><code>{current.state.reason}</code><p>触发规则：{current.state.trigger_rules?.join('、')||'—'}</p><p>未满足规则：{current.state.failed_rules?.join('、')||'—'}</p><p>不可用规则：{current.state.unavailable_rules?.join('、')||'—'}</p>
   <h3>关键指标</h3><div className="ml-metrics">{fields.map(([k,label])=><div key={k}><span>{label}</span><strong>{k==='turnover_intensity'?number(current.snapshot[k]):pct(current.snapshot[k])}</strong></div>)}</div>
   <h3>状态时间轴</h3><p className="ml-muted">仅列出已持久化日期，日期空档不会补造状态。</p><ol className="ml-timeline">{detail?.timeline.map(t=><li key={t.date}><strong>{t.date}</strong>{stage(t.state.state)}<small>{t.state.transition?`${t.state.transition.from_state} → ${t.state.transition.to_state} · ${t.state.transition.trigger_rule}`:t.state.reason}</small></li>)}</ol>
   <h3>规则证据</h3><div className="mainline-table-wrap"><Table><TableHeader><TableRow><TableHead>规则</TableHead><TableHead>实际值</TableHead><TableHead>阈值 / 运算</TableHead><TableHead>结果</TableHead></TableRow></TableHeader><TableBody>{detail?.rule_evidence.map(q=><TableRow key={q.rule_id}><TableCell>{q.rule_id}</TableCell><TableCell>{JSON.stringify(q.actual_value)??'NULL'}</TableCell><TableCell>{q.operator} {JSON.stringify(q.threshold)}</TableCell><TableCell>{q.passed===null?'不可用':q.passed?'满足':'未满足'}<small className="ml-sub">{q.reason}</small></TableCell></TableRow>)}</TableBody></Table></div>
   <h3>生命周期</h3><pre>{JSON.stringify(detail?.lifecycle,null,2)}</pre><h3>覆盖率与Freeze</h3><pre>{JSON.stringify({coverage:current.snapshot.metric_coverage_json,stage_frozen:current.state.stage_frozen,freeze_reason:current.state.freeze_reason},null,2)}</pre><h3>版本与运行来源</h3><pre>{JSON.stringify({rule_version:detail?.rule_version,profile:detail?.parameter_profile,run_id:current.state.run_id,sources:detail?.sources},null,2)}</pre>
  </div>}</SheetContent></Sheet>
 </main></Shell>;
}
